name: Pipeline CI/CD Principal (Sonar + AWS S3)

# Define os gatilhos (triggers)
on:
  # Gatilho 1: Para o DEPLOY (quando o merge na main acontece)
  push:
    branches:
      - "main"
      
  # Gatilho 2: Para o TESTE (quando um PR e aberto)
  pull_request:
    branches:
      - "main"
      - "homolog"
      - "develop"
      
  workflow_dispatch:

jobs:
  # --- TAREFA 1: ANALISE SONARCLOUD ---
  sonarcloud:
    name: Analise SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # --- DEPLOY NA AWS S3 ---
  deploy:
    name: Deploy no AWS S3
    needs: sonarcloud
    
    # So rode esta tarefa se o gatilho foi um PUSH para a branch MAIN
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 

      - name: Enviar arquivos para o S3
        run: |
          aws s3 sync . s3://test-ivory-devops --delete 

      - name: Invalidar cache do CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id E1E3LPP7E7HO6W --paths "/*"